version: '3'

services:
  mysql:
    image: mysql:8.0.19
    container_name: auth_user_DBC
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - db_data:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=soa_user
        - MYSQL_PASSWORD=0000
        - MYSQL_ROOT_PASSWORD=0000
        - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - "3380:3306"
    networks:
      - app-tier

  server:
    build:
      context: .
    restart: on-failure
    depends_on:
        - mysql
    environment:
      # NODE_ENV: docker
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8082:8082"
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - app-tier

networks:
    app-tier:
        # driver: bridge

volumes:
  db_data: