version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: x0r3k/soa_auth_user
    container_name: auth_user_cont
    env_file: .env
    environment:
      - NODE_ENV=docker
      - HTTP_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start